### ISSUE TITLE
Angle bracket being escaped

### ISSUE THREAD

**Issue by chawyehsu** [PrimalHQ/primal-web-app#35]
## Describe the bug
Angle bracket `<>` being escaped on web app.

### Steps to reproduce
post a note with `>`
![image](https://github.com/PrimalHQ/primal-web-app/assets/5764917/98845f61-cfa1-4a8a-8047-4976aa352717)
https://primal.net/e/note1pgern7q3qjlfqqmsxanf7wjmnf7d4mq604dyjllsx5xst0r285ysd62umv

### Expected behavior
Not being escaped.

### Environment
N/A

### Additional context
Work as expected on mobile app.

**Comment by moysa** [comment]
Thank you for reporting this. It should be fixed now.
