### ISSUE TITLE
Overflow on userinfo with long name

### ISSUE THREAD

**Issue by chawyehsu** [PrimalHQ/primal-web-app#36]
## Describe the bug
↓

### Steps to reproduce
https://primal.net/e/note1yhg2rygp2936rx82gugnr4qtnpqm6f6ky0ugnyjgcy6vzmucs5dqkn0f7j
![image](https://github.com/PrimalHQ/primal-web-app/assets/5764917/e293abe5-8448-4f80-98bf-ff427f3d3cce)

### Expected behavior
No overflow

### Environment
web app on chrome

### Additional context
N/A

**Comment by moysa** [comment]
Thank you for reporting this. It should be fixed now.
