### ISSUE TITLE
Only first link in the note is previewed

### ISSUE THREAD

**Issue by rockstardev** [PrimalHQ/primal-web-app#44]
As described in the title, when you are composing note, only first link will be previewed.

### Steps to reproduce
1. Start composing message
2. Enter two links, like: 

https://m.primal.net/HQHe.mp4
and
https://m.primal.net/HQHe.mp4
3. Only first link will be previewed

### Expected behavior
Both links are previewed

### Additional context
Here is a video that illustrates the bug:

https://github.com/PrimalHQ/primal-web-app/assets/5191402/ef364fed-01d6-4035-b2cd-bc39ddf7d60d

**Comment by moysa** [comment]
I believe this is fixed. Closing
