### ISSUE TITLE
Reply notes don't include the "root" marker

### ISSUE THREAD

**Issue by hzrd149** [PrimalHQ/primal-web-app#53]
## Describe the bug
When replying to a note, primal dose not attach the "root" marker tag defined in [NIP-10](https://github.com/nostr-protocol/nips/blob/master/10.md#marked-e-tags-preferred)
I don't know if this causes any issues for primal but it has been causing some replies not to show in my own client noStrudel due to how it loads threads.

noStrudel loads threads by getting the event id of the root event of the thread and then querying its relays for any kind 1 event that tags that note. `{kinds: [1], "#e": [<root id>]}`
Since the reply notes in primal don't include a `["e", <id>, "", "root"]` tag referencing the root note noStrudel isn't able to find them.

I would have opened a PR to fix this but I'm not familiar enough with the code base :disappointed: 
https://github.com/PrimalHQ/primal-web-app/blob/main/src/components/NewNote/EditBox/EditBox.tsx#L520-L523

### Steps to reproduce
Reply to a note and copy raw data of the event.

### Expected behavior
Reply notes should have the "e" tag of the root event marked with "root" so they can easily be found by other clients

**Comment by moysa** [comment]
This issue should now be fixed on the web app. The app now publishes notes as described in `PREFERRED` section of NIP-10. We still, however, support parsing notes that have the either `DEPRECATED` or `PREFERRED` NIP-10 tags. Closing.
