### ISSUE TITLE
URL links in nostr notes are lower-cased by primal leading to 404 errors

### ISSUE THREAD

**Issue by harrymmmm** [PrimalHQ/primal-web-app#54]
### Steps to reproduce
Steps to reproduce the behavior.

### Environment
 - Details that you think may affect.

**Comment by harrymmmm** [comment]
reproduce: hover over the URL and see the url has been lower-cased
expected: not lower-cased
example: npub17u5dneh8qjp43ecfxr6u5e9sjamsmxyuekrg2nlxrrk6nj9rsyrqywt4tp
os: ubuntu desktop
bug occurs with primal in both brave and firefox browsers
does NOT occur in iris.to nostr client

**Comment by moysa** [comment]
This should now be fixed. URLs in links now respect the case of the link as user wrote it.
