### ISSUE TITLE
Primal freezes if you type nostr:npub... in the new note box

### ISSUE THREAD

**Issue by basantagoswami** [PrimalHQ/primal-web-app#57]
## Describe the bug
I wanted to tag a nostr profile with this npub: npub1dy2t2h6xphjqqyqm8thp3m2c0fka8ekzgxjjdm475lzm8xtpzxlqdzcv99, so I started typing @xonghoti, but Primal couldn't fetch the profile and autocomplete it. So I decided to type nostr: and the paste in the npub right after that. But doing so freezes Primal completely and even hard refreshes don't fix it. I had to clear site data to make the new note box usable again, because Primal caches the previously typed data.

### Steps to reproduce
Type "npub:" in the box. Then start typing your npub, it will allow you to type till a few characters before freezing. If you paste in the entire pubkey, it will freeze automatically

### Expected behavior
Allow users to paste nostr:npub.. s and then autocomplete the profile name.

### Environment
I was using Chromium on Ubuntu.

**Comment by moysa** [comment]
Thank you for reporting this. It should be fixed now.
