### ISSUE TITLE
Broken avatar and banner on profile

### ISSUE THREAD

**Issue by anthony-robin** [PrimalHQ/primal-web-app#59]
My avatar and banner never get displayed on Primal. It always show default placeholders whereas in other clients such as Snort or Amethyst, they are properly displayed.

I manage my Nostr account from my own website publishing directly to relays (without going through Nostr clients profile management form) and my assets are attached to my own domain name.

(Note that sometimes, the real avatar shows for half second before being replaced by the placeholder)

Here are two screenshots: one from Snort and the other from Primal on the same profile.

### Snort

<img width="638" alt="Capture d’écran 2024-02-27 à 15 51 21" src="https://github.com/PrimalHQ/primal-web-app/assets/5428510/d4bc0a87-e4ff-4661-88be-ad914a696bc0">

### Primal

<img width="613" alt="Capture d’écran 2024-02-27 à 15 50 54" src="https://github.com/PrimalHQ/primal-web-app/assets/5428510/1880d15d-5536-4793-ab2e-fb1ab1f5994b">

How can I make my avatar and banner to show up on Primal in the same way as other clients ? Could it be a cache or CDN issue ?

Thank you for your help :)

**Comment by moysa** [comment]
Hi Anthony, could you please provide your npub or a link to your profile so that I can investigate the issue. Thank you.

**Comment by anthony-robin** [comment]
Sure ! 
How can I send you the npub privately (I would prefer to avoid exposing the account on Github publicly) ?

**Comment by moysa** [comment]
You can DM me over Nostr, here is my npub: npub19f2765hdx8u9lz777w7azed2wsn9mqkf2gvn67mkldx8dnxvggcsmhe9da

**Comment by anthony-robin** [comment]
DM sent, thanks !

**Comment by moysa** [comment]
The issue here has to do with redirection. This confused the image renderer into thinking there is no image. I added a double check. This issue should now be fixed. Closing.
